playlists:
- https://www.youtube.com/playlist?list=PLIzPbE6Bl1SpIGDRzUthWrgjRwOKJTCNx # pop
- https://music.youtube.com/playlist?list=PLIzPbE6Bl1So3o0LMLEK0lyXuwxlUCNBh # metal
- https://music.youtube.com/playlist?list=PLIzPbE6Bl1Sqgc0nHwZQuZ5wQLZ_vqEqv # evergreen
- https://music.youtube.com/playlist?list=PLIzPbE6Bl1So6PwZLnck5A1qcJRbY716N # cartoons
- https://music.youtube.com/playlist?list=PLIzPbE6Bl1SpeNL7mY9YF0jgY39u69xoV # italians
- https://music.youtube.com/playlist?list=PLIzPbE6Bl1Sqztlj0yxDGu2h0Ca_YskZ8 # christmas
# - https://music.youtube.com/browse/VLPLIzPbE6Bl1SrD7PZnyXf7mVnttL9ILtAW # summer
redis-host: localhost
jobs: 16
